# Generated by Django 3.2.9 on 2021-11-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A product with the given name already exists in the database.'}, max_length=100, unique=True)),
                ('unity_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('suppliers_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('freight_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('amount_in_stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PRODUCTS',
                'ordering': ('id',),
            },
        ),
    ]
