# Generated by Django 3.2.9 on 2021-11-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(error_messages={'unique': 'A product with the given name already exists in the database.'}, max_length=100, unique=True),
        ),
    ]
